# Generated by Django 3.2.8 on 2021-10-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('wiki_url', models.CharField(max_length=100)),
                ('rarity', models.PositiveIntegerField()),
                ('element', models.CharField(max_length=50)),
                ('weapon', models.CharField(max_length=50)),
            ],
        ),
    ]
