# Generated by Django 3.2.8 on 2021-10-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('wiki_url', models.CharField(max_length=100)),
                ('rarity', models.PositiveIntegerField()),
                ('element', models.CharField(max_length=50)),
                ('weapon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('wiki_url', models.CharField(max_length=100)),
                ('rarity', models.PositiveIntegerField()),
                ('element', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('wiki_url', models.CharField(max_length=100)),
                ('rarity', models.PositiveIntegerField()),
                ('element', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wyrmprint',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('wiki_url', models.CharField(max_length=100)),
                ('rarity', models.PositiveIntegerField()),
                ('affinity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('affinity_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
