# Generated by Django 3.2.8 on 2021-10-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyrmprint',
            name='ability_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wyrmprint',
            name='ability_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wyrmprint',
            name='ability_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
