# Generated by Django 3.2.8 on 2021-10-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyrmprint',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
