# Generated by Django 3.2.8 on 2021-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0002_auto_20211022_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyrmprint',
            name='affinity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wyrmprint',
            name='affinity_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
