# Generated by Django 3.2.8 on 2021-10-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0003_auto_20211022_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyrmprint',
            old_name='affinity',
            new_name='affinity_name',
        ),
    ]
