# Generated by Django 3.2.8 on 2021-10-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0004_weapon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='weapon',
            new_name='type',
        ),
    ]
