# Generated by Django 3.2.8 on 2021-12-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0004_weapon_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortraitAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
