# Generated by Django 3.2.8 on 2022-01-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0005_portraitability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portraitability',
            options={'verbose_name_plural': 'Portrait Abilities'},
        ),
    ]
