# Generated by Django 3.2.8 on 2021-11-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitefaq_order_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitefaq',
            name='slug',
        ),
    ]
