# Generated by Django 3.2.8 on 2021-10-22 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_data', '0004_rename_affinity_wyrmprint_affinity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=120)),
                ('title', models.CharField(max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=120)),
                ('title', models.CharField(max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=120)),
                ('title', models.CharField(max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulties', models.ManyToManyField(to='comps.CompDifficulty')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quests', to='comps.compsection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=120)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.CharField(max_length=100)),
                ('game_version', models.CharField(max_length=100)),
                ('clear_time', models.CharField(max_length=50)),
                ('clear_rate', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discussion_link', models.URLField()),
                ('video_link', models.URLField()),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comps', to='comps.compdifficulty')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comps', to='comps.compquest')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comps', to='comps.compsection')),
                ('shared_skill_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_shared_skill_1', to='game_data.adventurer')),
                ('shared_skill_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_shared_skill_2', to='game_data.adventurer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdventurerBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'LEAD_UNIT'), (2, 'UNIT_2'), (3, 'UNIT_3'), (4, 'UNIT_4')], default=1)),
                ('adventurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='builds', to='game_data.adventurer')),
                ('adventurer_dragon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_dragon', to='game_data.dragon')),
                ('adventurer_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_weapon', to='game_data.weapon')),
                ('adventurer_wp_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_1', to='game_data.wyrmprint')),
                ('adventurer_wp_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_2', to='game_data.wyrmprint')),
                ('adventurer_wp_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_3', to='game_data.wyrmprint')),
                ('adventurer_wp_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_4', to='game_data.wyrmprint')),
                ('adventurer_wp_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_5', to='game_data.wyrmprint')),
                ('adventurer_wp_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_6', to='game_data.wyrmprint')),
                ('adventurer_wp_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_7', to='game_data.wyrmprint')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='builds', to='comps.comp')),
            ],
        ),
    ]
