# Generated by Django 3.2.8 on 2021-10-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_data', '0005_rename_weapon_weapon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('game_version', models.CharField(max_length=100)),
                ('clear_time', models.CharField(max_length=50)),
                ('clear_rate', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discussion_link', models.URLField()),
                ('video_link', models.URLField()),
                ('adventurer_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1', to='game_data.adventurer')),
                ('adventurer_1_dragon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_dragon_1', to='game_data.dragon')),
                ('adventurer_1_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_weapon_1', to='game_data.weapon')),
                ('adventurer_wp_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1_wp_1', to='game_data.wyrmprint')),
                ('adventurer_wp_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1_wp_2', to='game_data.wyrmprint')),
                ('adventurer_wp_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1_wp_3', to='game_data.wyrmprint')),
                ('adventurer_wp_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1_wp_4', to='game_data.wyrmprint')),
                ('adventurer_wp_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1_wp_5', to='game_data.wyrmprint')),
                ('adventurer_wp_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1_wp_6', to='game_data.wyrmprint')),
                ('adventurer_wp_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_1_wp_7', to='game_data.wyrmprint')),
                ('shared_skill_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_shared_skill_1', to='game_data.adventurer')),
                ('shared_skill_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_shared_skill_2', to='game_data.adventurer')),
            ],
        ),
    ]
