# Generated by Django 3.2.8 on 2021-10-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='adventurer_wp_1',
            new_name='adventurer_1_wp_1',
        ),
        migrations.RenameField(
            model_name='comp',
            old_name='adventurer_wp_2',
            new_name='adventurer_1_wp_2',
        ),
        migrations.RenameField(
            model_name='comp',
            old_name='adventurer_wp_3',
            new_name='adventurer_1_wp_3',
        ),
        migrations.RenameField(
            model_name='comp',
            old_name='adventurer_wp_4',
            new_name='adventurer_1_wp_4',
        ),
        migrations.RenameField(
            model_name='comp',
            old_name='adventurer_wp_5',
            new_name='adventurer_1_wp_5',
        ),
        migrations.RenameField(
            model_name='comp',
            old_name='adventurer_wp_6',
            new_name='adventurer_1_wp_6',
        ),
        migrations.RenameField(
            model_name='comp',
            old_name='adventurer_wp_7',
            new_name='adventurer_1_wp_7',
        ),
    ]
