# Generated by Django 3.2.8 on 2021-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compquest',
            name='nav_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
