# Generated by Django 3.2.8 on 2021-10-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_compquest_nav_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='compquest',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compsection',
            name='nav_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compsection',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
