# Generated by Django 3.2.8 on 2021-10-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0002_auto_20211020_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_dragon',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_weapon',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_wp_1',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_wp_2',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_wp_3',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_wp_4',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_wp_5',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_wp_6',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1_wp_7',
        ),
    ]
