# Generated by Django 3.2.8 on 2021-10-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0005_rename_weapon_weapon_type'),
        ('comps', '0003_auto_20211020_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventurerBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer', to='game_data.adventurer')),
                ('adventurer_dragon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_dragon', to='game_data.dragon')),
                ('adventurer_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_weapon', to='game_data.weapon')),
                ('adventurer_wp_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_1', to='game_data.wyrmprint')),
                ('adventurer_wp_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_2', to='game_data.wyrmprint')),
                ('adventurer_wp_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_3', to='game_data.wyrmprint')),
                ('adventurer_wp_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_4', to='game_data.wyrmprint')),
                ('adventurer_wp_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_5', to='game_data.wyrmprint')),
                ('adventurer_wp_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_6', to='game_data.wyrmprint')),
                ('adventurer_wp_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_build_adventurer_wp_7', to='game_data.wyrmprint')),
            ],
        ),
    ]
