# Generated by Django 3.2.8 on 2021-10-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_comptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='comp_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comps', to='comps.comptype'),
        ),
    ]
