# Generated by Django 3.2.8 on 2021-10-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_auto_20211022_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='discussion_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comp',
            name='game_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comp',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
