# Generated by Django 3.2.8 on 2021-10-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0004_auto_20211022_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='notes',
            new_name='creators_notes',
        ),
        migrations.AddField(
            model_name='comp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
