# Generated by Django 3.2.8 on 2021-10-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0005_rename_weapon_weapon_type'),
        ('comps', '0005_auto_20211020_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_1',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_2',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_3',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='adventurer_4',
        ),
        migrations.AddField(
            model_name='adventurerbuild',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adventurer_builds', to='comps.comp'),
        ),
        migrations.AddField(
            model_name='adventurerbuild',
            name='slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LEAD_UNIT'), (2, 'UNIT_2'), (3, 'UNIT_3')], default=1),
        ),
        migrations.AlterField(
            model_name='adventurerbuild',
            name='adventurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comp_adventurer_builds', to='game_data.adventurer'),
        ),
    ]
