# Generated by Django 3.2.8 on 2021-10-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0005_auto_20211025_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='clear_rate_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comp',
            name='clear_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
