# Generated by Django 3.2.8 on 2021-10-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0006_auto_20211020_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', editable=False, max_length=120)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='adventurerbuild',
            name='slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LEAD_UNIT'), (2, 'UNIT_2'), (3, 'UNIT_3'), (4, 'UNIT_4')], default=1),
        ),
    ]
