# Generated by Django 3.2.8 on 2021-10-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0007_auto_20211020_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='compsection',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
