# Generated by Django 3.2.8 on 2021-10-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0007_compquest_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_dragon',
            new_name='dragon',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_weapon',
            new_name='weapon',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_wp_1',
            new_name='wyrmprint_1',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_wp_2',
            new_name='wyrmprint_2',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_wp_3',
            new_name='wyrmprint_3',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_wp_4',
            new_name='wyrmprint_4',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_wp_5',
            new_name='wyrmprint_5',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_wp_6',
            new_name='wyrmprint_6',
        ),
        migrations.RenameField(
            model_name='adventurerbuild',
            old_name='adventurer_wp_7',
            new_name='wyrmprint_7',
        ),
    ]
