# Generated by Django 3.2.8 on 2021-11-02 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0008_auto_20211028_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comp',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
