# Generated by Django 3.2.8 on 2021-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0009_auto_20211102_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='compquest',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
