# Generated by Django 3.2.8 on 2021-10-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0010_compquest_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='compdifficulty',
            name='quuest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='difficulties', to='comps.compquest'),
        ),
    ]
