# Generated by Django 3.2.8 on 2021-11-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0002_wyrmprint_image_id'),
        ('comps', '0010_compquest_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='helper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comp',
            name='helper_dragon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='helper', to='game_data.dragon'),
        ),
    ]
