# Generated by Django 3.2.8 on 2021-10-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0012_rename_quuest_compdifficulty_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compdifficulty',
            name='quest',
        ),
    ]
