# Generated by Django 3.2.8 on 2021-10-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0013_remove_compdifficulty_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='compquest',
            name='difficulties',
            field=models.ManyToManyField(to='comps.CompDifficulty'),
        ),
    ]
