# Generated by Django 3.2.8 on 2021-11-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0013_comp_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventurerbuild',
            name='slot',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'LEAD_UNIT'), (2, 'UNIT_2'), (3, 'UNIT_3'), (4, 'UNIT_4')], default=1, null=True),
        ),
    ]
