# Generated by Django 3.2.8 on 2021-10-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0014_compquest_difficulties'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comps', to='comps.compdifficulty'),
        ),
        migrations.AddField(
            model_name='comp',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comps', to='comps.compquest'),
        ),
        migrations.AddField(
            model_name='comp',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comps', to='comps.compsection'),
        ),
    ]
