# Generated by Django 3.2.8 on 2021-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0014_alter_adventurerbuild_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='compsection',
            name='hide_children',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='compsection',
            name='is_new',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
