# Generated by Django 3.2.8 on 2021-10-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0015_auto_20211020_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=120),
        ),
    ]
