# Generated by Django 3.2.8 on 2021-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0015_auto_20211110_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='compquest',
            name='image_offset',
            field=models.IntegerField(default=0),
        ),
    ]
