# Generated by Django 3.2.8 on 2021-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0016_compquest_image_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compquest',
            name='image_offset',
            field=models.IntegerField(default=-30),
        ),
    ]
