# Generated by Django 3.2.8 on 2021-11-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0018_remove_comp_game_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='parent_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='comps.comp'),
        ),
    ]
