# Generated by Django 3.2.8 on 2021-11-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0019_comp_parent_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='compsection',
            name='difficulties',
            field=models.ManyToManyField(to='comps.CompDifficulty'),
        ),
    ]
