# Generated by Django 3.2.8 on 2021-12-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_data', '0005_portraitability'),
        ('comps', '0020_compsection_difficulties'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurerbuild',
            name='portrait_ability_slot_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portrait_ability_1', to='game_data.portraitability'),
        ),
        migrations.AddField(
            model_name='adventurerbuild',
            name='portrait_ability_slot_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='portrait_ability_2', to='game_data.portraitability'),
        ),
    ]
